[build]
  base = "."
  command = "yarn install --frozen-lockfile && yarn workspace frontend build"
  publish = "packages/frontend/dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_SKIP_SECRETS_SCAN = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200