import {
  Scale,
  FileText,
  ShieldAlert,
  Ban,
  AlertTriangle,
  UserX,
  Mail,
} from "lucide-react";
import { Card } from "@/components/ui/card";
import { PageWrapper } from "@/components/PageWrapper";

export function TermsOfServicePage() {
  const lastUpdated = "March 1, 2026";

  return (
    <PageWrapper maxWidth="4xl">
      <div className="py-12">
        {/* Header */}
        <div className="mb-12">
          <div className="inline-flex items-center gap-2 bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 px-3 py-1.5 rounded-full text-xs font-medium mb-4">
            <Scale className="w-3.5 h-3.5" />
            Terms of Service
          </div>
          <h1 className="text-3xl md:text-4xl font-bold text-foreground mb-3">
            Terms of Service
          </h1>
          <p className="text-muted-foreground">Last updated: {lastUpdated}</p>
        </div>

        <div className="space-y-8">
          {/* Intro */}
          <Card className="p-6 md:p-8">
            <p className="text-muted-foreground leading-relaxed">
              Welcome to TrueHire. By accessing or using our platform, you agree
              to these Terms of Service. TrueHire is an AI-powered job safety
              platform designed to help newcomers to Canada evaluate job
              postings. Please read these terms carefully before using our
              services.
            </p>
          </Card>

          {[
            {
              icon: FileText,
              title: "1. Acceptance of Terms",
              content: [
                "By creating an account or using TrueHire, you confirm that you are at least 16 years of age and agree to be bound by these Terms.",
                "If you are using TrueHire on behalf of an organization, you represent that you have the authority to bind that organization to these Terms.",
                "We may update these Terms from time to time. Continued use of TrueHire after changes constitutes acceptance of the updated Terms.",
              ],
            },
            {
              icon: ShieldAlert,
              title: "2. Service Description",
              content: [
                "TrueHire provides AI-powered analysis of job postings using our TrueScore™ system, which evaluates postings across five dimensions: Authenticity, Hiring Activity, Resume Match, Recency, and Company Reputation.",
                "**TrueHire is a guidance tool, not a guarantee.** Our analysis provides informed recommendations but cannot guarantee the legitimacy or suitability of any job posting.",
                "The TrueScore™ is generated by machine learning models and heuristic rules. While we strive for accuracy, no automated system is perfect.",
                "**Always conduct your own independent research** before applying to any job or sharing personal information with a potential employer.",
              ],
            },
            {
              icon: Ban,
              title: "3. Acceptable Use",
              content: [
                "You may use TrueHire for personal, non-commercial job search and safety purposes.",
                "You must not use TrueHire to: scrape or bulk-download data, reverse-engineer our algorithms, harass or impersonate others, or submit intentionally misleading content.",
                "You must not attempt to circumvent rate limits, authentication, or other security measures.",
                "Automated access to TrueHire (bots, scrapers) is prohibited without prior written consent.",
              ],
            },
            {
              icon: AlertTriangle,
              title: "4. Disclaimer of Warranties",
              content: [
                'TrueHire is provided **"as is"** and **"as available"** without warranties of any kind, whether express or implied.',
                "We do not warrant that our analysis will be accurate, complete, or error-free. AI-generated assessments are probabilistic in nature.",
                "We are not responsible for the actions of employers, recruiters, or any third parties whose job postings are analyzed through our platform.",
                "Job listings displayed through our search feature are sourced from third-party APIs (Adzuna) and we do not control their accuracy or availability.",
              ],
            },
            {
              icon: UserX,
              title: "5. Limitation of Liability",
              content: [
                "To the maximum extent permitted by law, TrueHire and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the platform.",
                "This includes, but is not limited to: losses from applying to fraudulent job postings, missed employment opportunities, or any decisions made based on our TrueScore™ analysis.",
                "Our total liability for any claim shall not exceed the amount you paid to use TrueHire (which is currently $0, as the platform is free).",
              ],
            },
            {
              icon: Scale,
              title: "6. Intellectual Property",
              content: [
                "The TrueScore™ system, TrueHire brand, and all associated algorithms, designs, and content are the intellectual property of TrueHire.",
                "Your resume and personal data remain your property. By uploading content, you grant us a limited license to process it for the purpose of providing our services.",
                "User-submitted scam reports may be used to improve our detection models and may be shared in anonymized, aggregated form.",
              ],
            },
            {
              icon: Mail,
              title: "7. Contact & Governing Law",
              content: [
                "These Terms are governed by the laws of the Province of Ontario, Canada.",
                "For questions about these Terms, please visit our [Contact page](/contact).",
                "If any provision of these Terms is found unenforceable, the remaining provisions will continue in full force and effect.",
              ],
            },
          ].map((section) => (
            <Card key={section.title} className="p-6 md:p-8">
              <div className="flex items-center gap-3 mb-4">
                <div className="p-2 rounded-lg bg-primary/10">
                  <section.icon className="w-5 h-5 text-primary" />
                </div>
                <h2 className="text-xl font-semibold text-foreground">
                  {section.title}
                </h2>
              </div>
              <ul className="space-y-3">
                {section.content.map((item, i) => (
                  <li
                    key={i}
                    className="text-muted-foreground text-sm leading-relaxed pl-4 border-l-2 border-border"
                    dangerouslySetInnerHTML={{
                      __html: item
                        .replace(
                          /\*\*(.*?)\*\*/g,
                          '<strong class="text-foreground">$1</strong>',
                        )
                        .replace(
                          /\[(.*?)\]\((.*?)\)/g,
                          '<a href="$2" class="text-primary hover:underline">$1</a>',
                        ),
                    }}
                  />
                ))}
              </ul>
            </Card>
          ))}
        </div>
      </div>
    </PageWrapper>
  );
}
